### ISSUE TITLE
Ubuntu + nvidia, not loading correct libGL.so

### ISSUE THREAD

**Issue by Circuit8** [jellymann/mittsu#25]
````Ruby
require 'mittsu'

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
ASPECT = SCREEN_WIDTH.to_f / SCREEN_HEIGHT.to_f

renderer = Mittsu::OpenGLRenderer.new width: SCREEN_WIDTH, height: SCREEN_HEIGHT, title: 'Hello, World!'

scene = Mittsu::Scene.new

camera = Mittsu::PerspectiveCamera.new(75.0, ASPECT, 0.1, 1000.0)
camera.position.z = 5.0

box = Mittsu::Mesh.new(
  Mittsu::BoxGeometry.new(1.0, 1.0, 1.0),
  Mittsu::MeshBasicMaterial.new(color: 0x00ff00)
)

scene.add(box)

renderer.window.run do
  box.rotation.x += 0.1
  box.rotation.y += 0.1

  renderer.render(scene, camera)
end
````
````Ruby
/home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mittsu-0.1.3/lib/mittsu/renderers/opengl/opengl_lib.rb:30:in `dirname': no implicit conversion of nil into String (TypeError)
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mittsu-0.1.3/lib/mittsu/renderers/opengl/opengl_lib.rb:30:in `path'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mittsu-0.1.3/lib/mittsu/renderers/opengl_renderer.rb:8:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mittsu-0.1.3/lib/mittsu/renderers.rb:1:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/mittsu-0.1.3/lib/mittsu.rb:18:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from test.rb:1:in `<main>'
````

**Comment by jellymann** [comment]
Hi @Circuit8, Linux support is still a bit shaky at the moment since I haven't had a chance to test on many different configurations.

Can you please provide for me what hardware you are running on, as well as the result of the following commands:
`lspci -nnk | grep -i vga -A3 | grep 'in use'`
and
`ruby -e 'puts Dir.glob("/usr/lib*/**/lib*")' | grep GL`
and
`glxinfo | grep 'OpenGL core profile'`

**Comment by Circuit8** [comment]
Hi @jellymann thanks for getting back to me. Here are the details. Let me know if you need anything else
````
Ubuntu 15.10 64-bit
GeForce GTX 960
Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
````

````
Kernel driver in use: nvidia
````

````
/usr/lib/x86_64-linux-gnu/libEGL.so.1
/usr/lib/x86_64-linux-gnu/libGL.so.1
/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.4
/usr/lib/x86_64-linux-gnu/mesa/libGL.so
/usr/lib/x86_64-linux-gnu/libGLEW.so.1.10.0
/usr/lib/x86_64-linux-gnu/libGLU.a
/usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.10
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5
/usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4.8
/usr/lib/x86_64-linux-gnu/libGL.so
/usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.1
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.4.2
/usr/lib/x86_64-linux-gnu/libGL.so.352.79
/usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4.8.6
/usr/lib/x86_64-linux-gnu/libGLEWmx.so.1.10.0
/usr/lib/x86_64-linux-gnu/libGLESv1_CM.so
/usr/lib/x86_64-linux-gnu/libEGL.so.352.79
/usr/lib/x86_64-linux-gnu/libGLESv1_CM.so.352.79
/usr/lib/x86_64-linux-gnu/libGLESv2.so.352.79
/usr/lib/x86_64-linux-gnu/libGLESv2.so.2
/usr/lib/x86_64-linux-gnu/libQtOpenGL.so.4
/usr/lib/x86_64-linux-gnu/libGL.la
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl
/usr/lib/x86_64-linux-gnu/libGLU.so.1
/usr/lib/x86_64-linux-gnu/libQtOpenGL.so
/usr/lib/x86_64-linux-gnu/libGLEW.so.1.10
/usr/lib/x86_64-linux-gnu/libGLU.so
/usr/lib/i386-linux-gnu/libGLU.so.1.3.1
/usr/lib/i386-linux-gnu/libQtOpenGL.so.4.8
/usr/lib/i386-linux-gnu/libQtOpenGL.so.4.8.6
/usr/lib/i386-linux-gnu/libQtOpenGL.so.4
/usr/lib/i386-linux-gnu/libGLU.so.1
/usr/lib/libGL.so.1
/usr/lib/libreoffice/program/libOGLTranslo.so
````

````
OpenGL core profile version string: 4.4.0 NVIDIA 352.79
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
````

**Comment by jellymann** [comment]
@Circuit8 I've modified the OpenGL library loader for linux. Can you try run one of the examples from the `master` branch and see if it works for you now?

**Comment by Circuit8** [comment]
Hi, I ran `ruby 01_scene_example.rb` from the examples directory on `master` and this is what I got:

````
/home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `initialize': /usr/lib/x86_64-linux-gnu/libGL.so: cannot open shared object file: No such file or directory (Fiddle::DLError)
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `new'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `dlopen'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/opengl-bindings-1.6.0/lib/opengl_common.rb:20:in `load_lib'
	from /home/joshua/Programs/Ruby/mittsu/lib/mittsu/renderers/opengl_renderer.rb:8:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu/lib/mittsu/renderers.rb:1:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu/lib/mittsu.rb:18:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu/examples/example_helper.rb:2:in `<top (required)>'
	from 01_scene_example.rb:1:in `require_relative'
	from 01_scene_example.rb:1:in `<main>'
````

**Comment by jellymann** [comment]
@Circuit8 That's weird. According to Dir.glob that file ought to be there.

What does `ls -l /usr/lib/x86_64-linux-gnu/libGL.so` say? Maybe it's a dead symlink or something.

I have a feeling the "real" libGL is the one with the version number that matches your nVidia driver version. Can you try run the example like so:

`MITTSU_LIBGL_PATH=/usr/lib/x86_64-linux-gnu MITTSU_LIBGL_FILE=libGL.so.352.79 ruby 01_scene_example.rb`

**Comment by Circuit8** [comment]
`lrwxrwxrwx 1 root root 13 Oct  9  2015 /usr/lib/x86_64-linux-gnu/libGL.so -> mesa/libGL.so`

Ah yes that works when I run it with the command you just linked! So what does this mean?

**Comment by jellymann** [comment]
It means I still have some work to do on the automatic libGL loader for Linux. In the meantime, you should be able to get by by with the `MITTSU_LIBGL_FILE=libGL.so.352.79` environment variable for now until I get things fixed.

**Comment by jellymann** [comment]
@Circuit8 Can you please provide me with the output of ``ldconfig -p | grep 'libGL\.so'`?

**Comment by Circuit8** [comment]
````
libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so.1
libGL.so.1 (libc6,x86-64) => /usr/lib/libGL.so.1
````
@jellymann Let me know if you need anything else, I'm happy to help such a great project!

**Comment by jellymann** [comment]
@Circuit8 Thanks for your help! Sorry for making you run around like this. Your system appears to be quite different to mine, despite both running Ubuntu 16.04 with the nvidia proprietary driver.

I've been reading up on the driver you're using, there may be a conflict with regards to the libGL shared library:

> If there are other libraries whose "soname" conflicts with that of the NVIDIA libraries, ldconfig may create the wrong symlinks. It is recommended that you manually remove or rename conflicting libraries (be sure to rename clashing libraries to something that ldconfig will not look at -- we have found that prepending "XXX" to a library name generally does the trick), rerun 'ldconfig', and check that the correct symlinks were made. **An example of a library that often creates conflicts is "/usr/lib/mesa/libGL.so*"**.

(Emphasis added. [Reference](http://us.download.nvidia.com/XFree86/Linux-x86/352.79/README/installedcomponents.html))

Can you provide the output of `ldd /usr/bin/glxgears` as well as `ls -l /usr/lib/**/libGL.so*`?

**Comment by Circuit8** [comment]
@jellymann no problem at all. I seem to remember the process of getting the Nvidia driver set up on my machine was quite complicated so its possible I've got a strange set up.
````
linux-vdso.so.1 =>  (0x00007ffc9edfd000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f950be10000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f950bb08000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f950b7cd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f950b403000)
	libnvidia-tls.so.352.79 => /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.352.79 (0x00007f950b200000)
	libnvidia-glcore.so.352.79 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.352.79 (0x00007f950876b000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f9508559000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9508355000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f9508133000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557f7547d000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9507f2f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f9507d29000)
````

````
lrwxrwxrwx 1 root root      13 Oct  9  2015 /usr/lib/x86_64-linux-gnu/libGL.so -> mesa/libGL.so
lrwxrwxrwx 1 root root      15 Feb  9  2016 /usr/lib/x86_64-linux-gnu/libGL.so.1 -> libGL.so.352.79
-rwxr-xr-x 1 root root 1218248 Feb  9  2016 /usr/lib/x86_64-linux-gnu/libGL.so.352.79
````

**Comment by jellymann** [comment]
@Circuit8 Aha, looks like I should be able to sort this out.

ldconfig points to `/usr/lib/x86_64-linux-gnu/libGL.so.1` (which incidentally is what glxgears links to)
`/usr/lib/x86_64-linux-gnu/libGL.so.1` is a symlink to `/usr/lib/x86_64-linux-gnu/libGL.so.352.79`

Which means my new ldconfig patch #27 should solve the problem you're having. I just need to fix one or two things and merge it tonight after I get home. In the meantime, check out the `ds-use-ldconfig` branch and see if it works for you.

**Comment by Circuit8** [comment]
@jellymann 

I tried `ds-use-ldconfig` branch and this is what I got:

````
/home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `initialize': /usr/lib/x86_64-linux-gnu/libGL.so: cannot open shared object file: No such file or directory (Fiddle::DLError)
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `new'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/2.2.0/fiddle.rb:46:in `dlopen'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/opengl-bindings-1.6.0/lib/opengl_common.rb:20:in `load_lib'
	from /home/joshua/Programs/Ruby/mittsu_new/mittsu/lib/mittsu/renderers/opengl_renderer.rb:8:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu_new/mittsu/lib/mittsu/renderers.rb:1:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu_new/mittsu/lib/mittsu.rb:18:in `<top (required)>'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/joshua/Programs/Ruby/mittsu_new/mittsu/examples/example_helper.rb:2:in `<top (required)>'
	from 01_scene_example.rb:1:in `require_relative'
	from 01_scene_example.rb:1:in `<main>'
````

**Comment by jellymann** [comment]
@Circuit8 

That doesn't make a lot of sense. According to your ldconfig, it should be loading `libGL.so.1`, and not just `libGL.so`. That's just plain weird...

I've pushed a few more changes to the `ds-use-ldconfig` branch, notably debug support. Can you pull the new changes and run `DEBUG=true ruby 01_scene_example.rb`, the first few lines should give us some insight as to what the library loader is trying to do.

**Comment by Circuit8** [comment]
@jellymann 
Wait that's my bad! I was using the master branch when I thought I was on the `ds-use-ldconfig` branch. All seems to be working fine now. Thanks for your help. If I have new feature requests should I open them as issues? Cheers

**Comment by jellymann** [comment]
@Circuit8 I'm glad it's working, I had run out of ideas on how to fix the issue!

You are more than welcome to create feature requests as issues. Have fun with Mittsu 👍
